// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAn6vMuQiQlYPCkHD2z1b3tizaQFPnSv4',
    appId: '1:753494807140:web:3fc388eef84454fc294571',
    messagingSenderId: '753494807140',
    projectId: 'facebook-9a6a6',
    authDomain: 'facebook-9a6a6.firebaseapp.com',
    storageBucket: 'facebook-9a6a6.firebasestorage.app',
    measurementId: 'G-BK87R55C3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASCbHeE_N6lXCNtjHGqqQQCtS2Wc7_lUQ',
    appId: '1:753494807140:android:c2e3e9872c0ddee0294571',
    messagingSenderId: '753494807140',
    projectId: 'facebook-9a6a6',
    storageBucket: 'facebook-9a6a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB7YKB8_HAzyZNkiazcHU3dHm9SL34I0U',
    appId: '1:753494807140:ios:0d7be5cbe882353c294571',
    messagingSenderId: '753494807140',
    projectId: 'facebook-9a6a6',
    storageBucket: 'facebook-9a6a6.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB7YKB8_HAzyZNkiazcHU3dHm9SL34I0U',
    appId: '1:753494807140:ios:0d7be5cbe882353c294571',
    messagingSenderId: '753494807140',
    projectId: 'facebook-9a6a6',
    storageBucket: 'facebook-9a6a6.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAn6vMuQiQlYPCkHD2z1b3tizaQFPnSv4',
    appId: '1:753494807140:web:536df9e328d69aef294571',
    messagingSenderId: '753494807140',
    projectId: 'facebook-9a6a6',
    authDomain: 'facebook-9a6a6.firebaseapp.com',
    storageBucket: 'facebook-9a6a6.firebasestorage.app',
    measurementId: 'G-SW84DV98B8',
  );
}
